/** @type {String} */ export const DOWNLOAD_LOAD     = 'download.load'
/** @type {String} */ export const DOWNLOAD_ABORT    = 'download.abort'
/** @type {String} */ export const DOWNLOAD_ERROR    = 'download.error'
/** @type {String} */ export const DOWNLOAD_TIMEOUT  = 'download.timeout'
/** @type {String} */ export const DOWNLOAD_PROGRESS = 'download.progress'

/** @type {String} */ export const UPLOAD_LOAD     = 'upload.load'
/** @type {String} */ export const UPLOAD_ABORT    = 'upload.abort'
/** @type {String} */ export const UPLOAD_ERROR    = 'upload.error'
/** @type {String} */ export const UPLOAD_TIMEOUT  = 'upload.timeout'
/** @type {String} */ export const UPLOAD_PROGRESS = 'upload.progress'
