import sh from '../src'

export default function ({ address, file }) {
  sh.commands.loadConfig({
    address, // @esdoc address: '192.168.1.121',
    file, // @esdoc file: 'custom-config.txt',
    timeout: 0
  })
    .then(response => {
      console.log('response:', response)
      console.log('>>>', JSON.stringify(response.data, null, 2))
      // >>> {
      //   "file": "/sd/config-override",
      //   "configText": "; DO NOT EDIT THIS FILE\n  ;Steps per unit:\n  M92 X80.00000 Y80.00000 Z1600.00000 \n  ;Acceleration mm/sec^2:\n  M204 S3000.00000 \n  ;X- Junction Deviation, Z- Z junction deviation, S - Minimum Planner speed mm/sec:\n  M205 X0.05000 Z-1.00000 S0.00000\n  ;Max cartesian feedrates in mm/sec:\n  M203 X500.00000 Y500.00000 Z5.00000 S-1.00000\n  ;Max actuator feedrates in mm/sec:\n  M203.1 X500.00000 Y500.00000 Z5.00000 \n  ;Digipot Motor currents:\n  M907 X1.50000 Y1.50000 Z1.50000 A1.50000 \n  ;E Steps per mm:\n  M92 E140.0000 P57988\n  ;E Filament diameter:\n  M200 D0.0000 P57988\n  ;E retract length, feedrate:\n  M207 S3.0000 F2700.0000 Z0.0000 Q6000.0000 P57988\n  ;E retract recover length, feedrate:\n  M208 S0.0000 F480.0000 P57988\n  ;E acceleration mm/sec²:\n  M204 E500.0000 P57988\n  ;E max feed rate mm/sec:\n  M203 E50.0000 P57988\n  ;PID settings, i_max, max_pwm:\n  M301 S0 P10.0000 I0.3000 D200.0000 X255.0000 Y255\n  ;Max temperature setting:\n  M143 S0 P300.0000\n  ;PID settings, i_max, max_pwm:\n  M301 S1 P10.0000 I0.3000 D200.0000 X255.0000 Y255\n  ;Max temperature setting:\n  M143 S1 P300.0000\n  ;Home offset (mm):\n  M206 X0.00 Y0.00 Z0.00",
      //   "config": [
      //     {
      //       "gcode": "M92 X80.00000 Y80.00000 Z1600.00000",
      //       "description": "DO NOT EDIT THIS FILE\nSteps per unit"
      //     },
      //     {
      //       "gcode": "M204 S3000.00000",
      //       "description": "Acceleration mm/sec^2"
      //     },
      //     {
      //       "gcode": "M205 X0.05000 Z-1.00000 S0.00000",
      //       "description": "X- Junction Deviation, Z- Z junction deviation, S - Minimum Planner speed mm/sec"
      //     },
      //     {
      //       "gcode": "M203 X500.00000 Y500.00000 Z5.00000 S-1.00000",
      //       "description": "Max cartesian feedrates in mm/sec"
      //     },
      //     {
      //       "gcode": "M203.1 X500.00000 Y500.00000 Z5.00000",
      //       "description": "Max actuator feedrates in mm/sec"
      //     },
      //     {
      //       "gcode": "M907 X1.50000 Y1.50000 Z1.50000 A1.50000",
      //       "description": "Digipot Motor currents"
      //     },
      //     {
      //       "gcode": "M92 E140.0000 P57988",
      //       "description": "E Steps per mm"
      //     },
      //     {
      //       "gcode": "M200 D0.0000 P57988",
      //       "description": "E Filament diameter"
      //     },
      //     {
      //       "gcode": "M207 S3.0000 F2700.0000 Z0.0000 Q6000.0000 P57988",
      //       "description": "E retract length, feedrate"
      //     },
      //     {
      //       "gcode": "M208 S0.0000 F480.0000 P57988",
      //       "description": "E retract recover length, feedrate"
      //     },
      //     {
      //       "gcode": "M204 E500.0000 P57988",
      //       "description": "E acceleration mm/sec²"
      //     },
      //     {
      //       "gcode": "M203 E50.0000 P57988",
      //       "description": "E max feed rate mm/sec"
      //     },
      //     {
      //       "gcode": "M301 S0 P10.0000 I0.3000 D200.0000 X255.0000 Y255",
      //       "description": "PID settings, i_max, max_pwm"
      //     },
      //     {
      //       "gcode": "M143 S0 P300.0000",
      //       "description": "Max temperature setting"
      //     },
      //     {
      //       "gcode": "M301 S1 P10.0000 I0.3000 D200.0000 X255.0000 Y255",
      //       "description": "PID settings, i_max, max_pwm"
      //     },
      //     {
      //       "gcode": "M143 S1 P300.0000",
      //       "description": "Max temperature setting"
      //     },
      //     {
      //       "gcode": "M206 X0.00 Y0.00 Z0.00",
      //       "description": "Home offset (mm)"
      //     }
      //   ]
      // }
    })
    .catch(error => {
      console.log(`${error.type}: ${error.message}`, error.response)
    })
}
